insert into students (id, cnp, address, email, password, name, study_group) values (1, '15812252590', '28 Stoughton Road', 'kgianullo0@irs.gov', 'qwerty', 'Karita Gianullo', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (2, '13410130574', '33151 Harbort Road', 'nnorton1@shinystat.com', 'qwerty', 'Niki Norton', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (3, '11056472443', '14 Brown Plaza', 'rpesek2@amazon.de', 'default2', 'Ruthie Pesek', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (4, '16806722461', '96512 Coolidge Court', 'pomullally3@nytimes.com', 'default2', 'Patric O''Mullally', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (5, '14166084789', '649 David Terrace', 'cskerm4@wikia.com', 'qwerty', 'Cristina Skerm', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (6, '17695533325', '8 Petterle Alley', 'emcnabb5@cdbaby.com', 'default1', 'Edy McNabb', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (7, '13377101098', '232 Forster Drive', 'tfraschini6@nhs.uk', 'default1', 'Tory Fraschini', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (8, '19028574299', '79 Evergreen Place', 'jbundy7@tripadvisor.com', 'default2', 'Jenilee Bundy', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (9, '11778487703', '860 Bellgrove Hill', 'hissatt8@typepad.com', 'qwerty', 'Hope Issatt', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (10, '17540366379', '2798 Rigney Street', 'ethrush9@cbc.ca', 'default1', 'Elsie Thrush', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (11, '18164980629', '8609 Moland Court', 'hyeabsleya@aol.com', 'default1', 'Hermina Yeabsley', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (12, '12329020144', '62449 Coleman Junction', 'sscopynb@vimeo.com', 'default2', 'Sigfrid Scopyn', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (13, '19751633843', '095 Cody Alley', 'bbradnockec@blogspot.com', 'default1', 'Brigid Bradnocke', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (14, '15964081066', '40441 Bartelt Pass', 'mcoldicottd@telegraph.co.uk', 'default', 'Marigold Coldicott', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (15, '13910260000', '5741 Upham Center', 'mpentycoste@infoseek.co.jp', 'qwerty', 'Mal Pentycost', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (16, '15778422666', '0815 Sycamore Crossing', 'gwattersf@kickstarter.com', 'qwerty', 'Georgie Watters', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (17, '16875058469', '634 Park Meadow Junction', 'kwinneyg@businesswire.com', 'default2', 'Kiele Winney', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (18, '12160079341', '42 Lake View Place', 'mclapisonh@imdb.com', 'default2', 'Marty Clapison', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (19, '15111210221', '7 Prentice Plaza', 'asantusi@g.co', 'default', 'Andriana Santus', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (20, '17569304705', '0110 Melvin Terrace', 'cwheatlandj@alexa.com', 'default2', 'Carmelina Wheatland', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (21, '11751594078', '5 Clove Road', 'mquernelk@reverbnation.com', 'default1', 'Marcy Quernel', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (22, '16219279659', '1 Towne Parkway', 'cleynaghl@sourceforge.net', 'qwerty', 'Cosetta Leynagh', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (23, '14571425744', '93778 Hollow Ridge Place', 'mtwiggem@smh.com.au', 'default1', 'Mamie Twigge', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (24, '17869363024', '68 Green Place', 'ddittyn@wunderground.com', 'default1', 'Drew Ditty', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (25, '19091210808', '5803 Montana Drive', 'btiernano@marriott.com', 'default', 'Brit Tiernan', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (26, '16476980543', '75425 Shopko Point', 'sjimenop@mediafire.com', 'default1', 'Sarena Jimeno', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (27, '14978505445', '51 Harper Crossing', 'mschlagmanq@blogger.com', 'default1', 'Malcolm Schlagman', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (28, '10767276708', '58467 Bultman Alley', 'rfannerr@altervista.org', 'default2', 'Roy Fanner', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (29, '11480918028', '36302 Farragut Avenue', 'ljanotas@businessweek.com', 'default2', 'Livia Janota', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (30, '14451715364', '8 Mariners Cove Circle', 'obeckent@flavors.me', 'default', 'Orv Becken', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (31, '12494190180', '9 Moose Road', 'rfairmanu@businesswire.com', 'default', 'Robinetta Fairman', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (32, '18248981343', '9 5th Street', 'isprossonv@typepad.com', 'default', 'Ira Sprosson', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (33, '10053440400', '9661 Fallview Drive', 'dswidenbankw@reverbnation.com', 'default1', 'Dasie Swidenbank', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (34, '12929801320', '7 Novick Place', 'lstirtonx@behance.net', 'default1', 'Lenka Stirton', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (35, '18401405286', '28 Monument Street', 'sgarrawayy@scribd.com', 'default2', 'Sophie Garraway', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (36, '16058606330', '7 Bluejay Road', 'soglesbeez@photobucket.com', 'qwerty', 'Suzann Oglesbee', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (37, '11374899589', '86767 Golden Leaf Park', 'cwyeth10@desdev.cn', 'default', 'Christi Wyeth', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (38, '16027251502', '3371 Gateway Hill', 'dnurny11@timesonline.co.uk', 'default1', 'Desdemona Nurny', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (39, '17801735993', '2 Hazelcrest Center', 'cjoannet12@apache.org', 'qwerty', 'Costa Joannet', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (40, '14043382010', '21811 Fisk Court', 'ostrapp13@telegraph.co.uk', 'default1', 'Ora Strapp', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (41, '18290662185', '3 Eagle Crest Drive', 'gwroth14@yahoo.co.jp', 'default', 'Garwin Wroth', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (42, '14251176359', '53743 Cordelia Place', 'hmacnockater15@squarespace.com', 'qwerty', 'Hyacintha MacNockater', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (43, '11919261815', '6 Dixon Hill', 'fdoggerell16@so-net.ne.jp', 'default', 'Ferdie Doggerell', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (44, '19098456602', '2701 Kinsman Junction', 'cgoodbur17@house.gov', 'default', 'Cecil Goodbur', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (45, '15143983629', '43776 Eagan Park', 'drye18@google.fr', 'qwerty', 'Doroteya Rye', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (46, '16446191941', '90680 Pepper Wood Pass', 'csleeman19@privacy.gov.au', 'default', 'Chrysler Sleeman', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (47, '17479608818', '55 Merry Court', 'cburnet1a@pcworld.com', 'default1', 'Cordi Burnet', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (48, '11320265650', '6017 Oak Valley Pass', 'tstoneham1b@google.fr', 'default2', 'Tallou Stoneham', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (49, '17728863162', '3 Atwood Alley', 'tjacquemot1c@newyorker.com', 'default2', 'Teodor Jacquemot', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (50, '11085562615', '558 Norway Maple Road', 'slowrey1d@dropbox.com', 'default', 'Selby Lowrey', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (51, '14111731329', '01446 Shopko Court', 'dmagrane1e@rambler.ru', 'default2', 'Davine Magrane', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (52, '13792680544', '71035 Bunting Circle', 'rvail1f@goo.ne.jp', 'default1', 'Rozanne Vail', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (53, '10483750514', '3 Rieder Road', 'mmarmyon1g@behance.net', 'qwerty', 'Marlena Marmyon', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (54, '11084415610', '7589 Hagan Plaza', 'lpotkins1h@pagesperso-orange.fr', 'default1', 'Liesa Potkins', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (55, '12487849817', '4308 Farwell Place', 'crowston1i@amazon.co.jp', 'default2', 'Clarisse Rowston', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (56, '16010989955', '76 Annamark Point', 'smadden1j@reference.com', 'qwerty', 'Sisely Madden', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (57, '13118962622', '00358 Hovde Drive', 'lhenken1k@go.com', 'default1', 'Lorena Henken', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (58, '12392985206', '7 Sunfield Alley', 'deberst1l@about.com', 'default', 'Douglass Eberst', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (59, '19906662144', '9949 Moland Alley', 'pchristophle1m@msn.com', 'default', 'Papagena Christophle', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (60, '13556825896', '4 School Alley', 'mdobbs1n@drupal.org', 'default', 'Mallissa Dobbs', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (61, '16093950402', '60 Ryan Drive', 'jsagerson1o@fda.gov', 'default2', 'Josefina Sagerson', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (62, '11681408537', '905 Anniversary Lane', 'gjaze1p@ocn.ne.jp', 'default1', 'Gabbey Jaze', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (63, '10026690798', '78 Del Sol Way', 'mtanby1q@unesco.org', 'default2', 'Marie-jeanne Tanby', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (64, '10854670349', '309 Waywood Point', 'nolechnowicz1r@nyu.edu', 'qwerty', 'Neilla Olechnowicz', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (65, '11037056779', '904 Grasskamp Plaza', 'adaybell1s@miitbeian.gov.cn', 'default2', 'Aurie Daybell', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (66, '17499504530', '97136 Straubel Point', 'rmacfarlane1t@uol.com.br', 'default2', 'Russ MacFarlane', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (67, '14743686105', '6 Ridge Oak Crossing', 'ftunnow1u@state.tx.us', 'default', 'Franky Tunnow', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (68, '19119205218', '56283 Farmco Parkway', 'bisacq1v@flavors.me', 'default1', 'Baudoin Isacq', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (69, '16232537364', '5 Carberry Terrace', 'zwrintmore1w@yelp.com', 'qwerty', 'Zoe Wrintmore', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (70, '10526294581', '514 Novick Court', 'bpundy1x@mapy.cz', 'default', 'Betsy Pundy', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (71, '16978725443', '16 Swallow Center', 'gmcmurraya1y@miitbeian.gov.cn', 'default2', 'Giacinta McMurraya', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (72, '16394415546', '33 Birchwood Street', 'sbridger1z@oaic.gov.au', 'qwerty', 'Sadye Bridger', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (73, '13829464556', '931 Northview Court', 'lmccullen20@rakuten.co.jp', 'default2', 'Lynett McCullen', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (74, '18482548990', '8 Derek Hill', 'robeirne21@wisc.edu', 'default', 'Rebe O''Beirne', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (75, '12027457413', '22 Annamark Junction', 'tbrockie22@washingtonpost.com', 'qwerty', 'Tova Brockie', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (76, '19210692700', '12 Glacier Hill Point', 'bbrabben23@studiopress.com', 'default1', 'Burgess Brabben', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (77, '18338094022', '95 Fuller Point', 'apester24@samsung.com', 'default', 'Abigail Pester', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (78, '17494633211', '3 Roth Junction', 'awhickman25@marriott.com', 'default1', 'Aileen Whickman', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (79, '12712006339', '23 Carberry Pass', 'atreen26@google.com.br', 'default2', 'Angil Treen', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (80, '13493193165', '06 Quincy Trail', 'cshackleton27@wikispaces.com', 'default1', 'Cristal Shackleton', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (81, '12916980044', '23 Swallow Circle', 'mschustl28@xing.com', 'default1', 'Madlen Schustl', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (82, '14197188912', '120 Springview Crossing', 'tcrispe29@mail.ru', 'default', 'Trix Crispe', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (83, '11473745356', '924 Carey Way', 'blawee2a@epa.gov', 'default1', 'Bernetta Lawee', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (84, '11924569572', '3237 Fieldstone Way', 'bmizzen2b@homestead.com', 'default1', 'Bathsheba Mizzen', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (85, '18922361184', '963 Gulseth Road', 'vmountfort2c@census.gov', 'default1', 'Vic Mountfort', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (86, '18383507912', '559 Reindahl Way', 'ksommer2d@cnbc.com', 'qwerty', 'Kean Sommer', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (87, '11665869804', '8 Kipling Pass', 'vmacalpine2e@nbcnews.com', 'default1', 'Vin MacAlpine', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (88, '14713677071', '80808 Marcy Junction', 'oyankin2f@technorati.com', 'default', 'Ollie Yankin', 5);
insert into students (id, cnp, address, email, password, name, study_group) values (89, '10527690721', '775 Coolidge Street', 'gwilcocke2g@imdb.com', 'default1', 'Godard Wilcocke', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (90, '17860900558', '91 Eagan Terrace', 'dgodin2h@networksolutions.com', 'default2', 'Dion Godin', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (91, '19701456881', '59 Spenser Street', 'nfilson2i@yellowbook.com', 'default', 'Nelie Filson', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (92, '10946086817', '040 Forest Run Street', 'ssloley2j@amazon.co.jp', 'default2', 'Simeon Sloley', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (93, '13065682855', '098 Eagle Crest Parkway', 'efrugier2k@tiny.cc', 'qwerty', 'Esme Frugier', 3);
insert into students (id, cnp, address, email, password, name, study_group) values (94, '18775579430', '9 Menomonie Hill', 'esaffin2l@businessinsider.com', 'default', 'Ellsworth Saffin', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (95, '14151169324', '25 Oneill Alley', 'kantyukhin2m@npr.org', 'default1', 'Keen Antyukhin', 4);
insert into students (id, cnp, address, email, password, name, study_group) values (96, '13990516619', '99 Arapahoe Drive', 'ssuddock2n@hibu.com', 'default2', 'Suzy Suddock', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (97, '15109250415', '15583 Nelson Pass', 'mmaryon2o@sciencedaily.com', 'qwerty', 'Marijn Maryon', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (98, '16915088610', '9 Homewood Point', 'bmarkova2p@reference.com', 'default1', 'Brook Markova', 1);
insert into students (id, cnp, address, email, password, name, study_group) values (99, '17874277595', '3531 Cody Pass', 'glangtry2q@who.int', 'default1', 'Gnni Langtry', 2);
insert into students (id, cnp, address, email, password, name, study_group) values (100, '18836160142', '61 Fulton Junction', 'ecuncliffe2r@php.net', 'qwerty', 'Erinn Cuncliffe', 4);
